### ISSUE TITLE
Error in aux_files/string_ensembl_uniprot_map.pkl

### ISSUE THREAD

**Issue by sauloapp** [rejuve-bio/biocypher-kg#4]
The string_ensembl_uniprot_map.pkl dict is mapping Ensembl ids to Uniprot record name. But it should map to Uniprot accession instead.
Thanks!

**Comment by Habush** [comment]
Hi Saulo,

The reason we're using Ensembl IDs as a key is because STRING uses Ensembl IDs for proteins. Please check the files in the [download](https://string-db.org/cgi/download?species_text=Homo+sapiens) section

**Comment by sauloapp** [comment]
Hmm... maybe I was not clear enough... The string_ensembl_uniprot_map.pkl maps, for instance: 
ENSP00000000233  to  ARF5
ARF5 is the name of the Uniprot record.  But it should map
ENSP00000000233 to  P84085
that is the Uniprot accession.

**Comment by Habush** [comment]
I see. In that case, it should be fixed. @dawit-melka Please look at this.
